"""Migrations

Revision ID: 021a6b83b644
Revises: 21d84825236e
Create Date: 2022-11-14 21:51:56.539479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021a6b83b644'
down_revision = '21d84825236e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
