"""Migrations

Revision ID: f6d7c2ae1a51
Revises: 021a6b83b644
Create Date: 2022-11-14 21:58:05.847300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d7c2ae1a51'
down_revision = '021a6b83b644'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
