version: '3'

services:
  web:
    container_name: web
    image: nginx:latest
    depends_on:
      - user_service
      - profile_service
      - pot_service
      - durak_service
      - chat_service
      - like_service
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - web
    command: certonly --webroot --webroot-path=/var/www/html --email sermed512@gmail.com --agree-tos --no-eff-email --force-renewal -d likepoker.online -d www.likepoker.online
  durak_db:
    image: postgres:latest
    volumes:
      - postgres_data_durak:/var/lib/postgresql/data/
    env_file:
      - .docker.env
      - .env
    environment:
      POSTGRES_USER: ${PG_DURAK_USER}
      POSTGRES_PASSWORD: ${PG_DURAK_PASSWORD}
      POSTGRES_DB: ${PG_DURAK_DB}
    expose:
      - 5432
  durak_service:
    image: like-games-durak:latest
    build: ./services/durak/
    volumes:
      - ./services/durak/app/:/app/
    env_file:
      - .admin.env
      - .docker.env
      - .env
      - .python.env
      - .site.env
    expose:
      - 8080
    depends_on:
      - durak_db
  chat_db:
    image: postgres:latest
    volumes:
      - postgres_data_chat:/var/lib/postgresql/data/
    env_file:
      - .docker.env
      - .env
    environment:
      POSTGRES_USER: ${PG_CHAT_USER}
      POSTGRES_PASSWORD: ${PG_CHAT_PASSWORD}
      POSTGRES_DB: ${PG_CHAT_DB}
    expose:
      - 5432
  chat_service:
    image: like-games-chat:latest
    build: ./services/chat/
    volumes:
      - ./services/chat/app/:/app/
    env_file:
      - .admin.env
      - .docker.env
      - .env
      - .python.env
      - .site.env
    expose:
      - 8080
    depends_on:
      - chat_db
  pot_db:
    image: postgres:latest
    volumes:
      - postgres_data_pot:/var/lib/postgresql/data/
    env_file:
      - .docker.env
      - .env
    environment:
      POSTGRES_USER: ${PG_POT_USER}
      POSTGRES_PASSWORD: ${PG_POT_PASSWORD}
      POSTGRES_DB: ${PG_POT_DB}
    expose:
      - 5432
  pot_service:
    image: like-games-pot:latest
    build: ./services/pot/
    volumes:
      - ./services/pot/app/:/app/
    env_file:
      - .admin.env
      - .docker.env
      - .env
      - .python.env
      - .site.env
    expose:
      - 8080
    depends_on:
      - pot_db
  profile_db:
    image: postgres:latest
    volumes:
      - postgres_data_profile:/var/lib/postgresql/data/
    env_file:
      - .docker.env
      - .env
    environment:
      POSTGRES_USER: ${PG_PROFILE_USER}
      POSTGRES_PASSWORD: ${PG_PROFILE_PASSWORD}
      POSTGRES_DB: ${PG_PROFILE_DB}
    expose:
      - 5432
  profile_service:
    image: like-games-profile:latest
    build: ./services/profile/
    volumes:
      - ./services/profile/app/:/app/
    env_file:
      - .admin.env
      - .docker.env
      - .env
      - .python.env
      - .site.env
    expose:
      - 8080
    depends_on:
      - profile_db
  user_db:
    image: postgres:latest
    volumes:
      - postgres_data_user:/var/lib/postgresql/data/
    env_file:
      - .docker.env
      - .env
    environment:
      POSTGRES_USER: ${PG_USER_USER}
      POSTGRES_PASSWORD: ${PG_USER_PASSWORD}
      POSTGRES_DB: ${PG_USER_DB}
    expose:
      - 5432
  user_service:
    image: like-games-user:latest
    build: ./services/user/
    volumes:
      - ./services/user/app/:/app/
    env_file:
      - .admin.env
      - .docker.env
      - .env
      - .jwt.env
      - .python.env
    expose:
      - 8080
    depends_on:
      - user_db
  like_service:
    image: like-games-like:latest
    build: ./services/like/
    volumes:
      - ./services/like/:/app/
    env_file:
      - .c++.env
      - .docker.env
    expose:
      - 8080

volumes:
  certbot-etc:
  certbot-var:
  web-root:

  postgres_data_durak:
  postgres_data_chat:
  postgres_data_pot:
  postgres_data_profile:
  postgres_data_user:
