"""Migrations

Revision ID: 1d49e04e6ac3
Revises: 4eb4a380d4e7
Create Date: 2022-11-14 21:51:56.343300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d49e04e6ac3'
down_revision = '4eb4a380d4e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
