"""Migrations

Revision ID: 4f975c9f3978
Revises: d8780d521a87
Create Date: 2022-11-14 22:03:26.362223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f975c9f3978'
down_revision = 'd8780d521a87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usermodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('registration_type', sa.Enum('provided', 'telegram', name='registrationtypeenum'), nullable=True),
    sa.Column('join', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usermodel_email'), 'usermodel', ['email'], unique=True)
    op.create_index(op.f('ix_usermodel_id'), 'usermodel', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usermodel_id'), table_name='usermodel')
    op.drop_index(op.f('ix_usermodel_email'), table_name='usermodel')
    op.drop_table('usermodel')
    # ### end Alembic commands ###
