"""Migrations

Revision ID: d8780d521a87
Revises: 1d49e04e6ac3
Create Date: 2022-11-14 21:58:18.339633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8780d521a87'
down_revision = '1d49e04e6ac3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
